import { useMemo, useState } from 'react';
import { marked } from 'marked';
import { api } from '../api/client';
import { usePoll } from '../hooks/usePoll';

export function ReportView() {
  const { data, error, loading, refresh } = usePoll(() => api.report(), 5000, true);
  const [raw, setRaw] = useState(false);

  const html = useMemo(() => {
    if (!data?.content) return '';
    return marked.parse(data.content, { async: false }) as string;
  }, [data?.content]);

  return (
    <div className="view report-view">
      <div className="view__header">
        <h1>Report</h1>
        <p>Generated by the Report agent once a task's sub-tasks finish.</p>
      </div>

      <div className="toolbar">
        <div className="tabs">
          <button type="button" className={`tab${!raw ? ' tab--active' : ''}`} onClick={() => setRaw(false)}>
            Rendered
          </button>
          <button type="button" className={`tab${raw ? ' tab--active' : ''}`} onClick={() => setRaw(true)}>
            Raw
          </button>
        </div>
        <div className="toolbar__actions">
          {data?.updatedAt && (
            <span className="toolbar__hint">Updated {new Date(data.updatedAt).toLocaleString()}</span>
          )}
          <button type="button" onClick={refresh} disabled={loading}>
            Refresh
          </button>
        </div>
      </div>

      {error && <div className="banner banner--danger">{error}</div>}

      {!data?.exists ? (
        <div className="empty-state">No report yet — finish a task in Chat and it'll show up here.</div>
      ) : raw ? (
        <pre className="log-pane">{data.content}</pre>
      ) : (
        <div className="markdown-body" dangerouslySetInnerHTML={{ __html: html }} />
      )}
    </div>
  );
}
